<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <BuildInParallel>false</BuildInParallel>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <VersionPrefix>1.0.0-beta010</VersionPrefix>
    <VersionSuffix Condition="'$(Configuration)'=='Debug'">build$([System.DateTime]::UtcNow.ToString(`yyyyMMddHHmm`))</VersionSuffix>
    <Company>Limbo</Company>
    <Product>Skybrud.Social</Product>
    <Authors>Anders Bjerner</Authors>
    <Copyright>Copyright © $([System.DateTime]::UtcNow.ToString(`yyyy`))</Copyright>
    <Description>Authentication and service implementation for the GitHub API.</Description>
  </PropertyGroup>

  <!-- Information for the NuGet package -->
  <PropertyGroup>
    <PackageId>Skybrud.Social.GitHub</PackageId>
    <PackageTags>GitHub, Graph, API, Skybrud, Social, OAuth, JSON, Limbo</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://packages.limbo.works/skybrud.social.github/</PackageProjectUrl>
    <PackageIcon>Limbo.png</PackageIcon>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/abjerner/Skybrud.Social.GitHub</RepositoryUrl>
  </PropertyGroup>

  <!-- Include NuGet dependencies -->
  <ItemGroup>
    <PackageReference Include="Skybrud.Essentials.Http" Version="1.1.0" />
  </ItemGroup>

  <!-- Include package icon for NuGet -->
  <ItemGroup>
    <Content Include="../build/Limbo.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <!-- Generate XML documentation -->
  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

</Project>